### ISSUE TITLE
Magento 2.4.x Compability

### ISSUE THREAD

**Issue by barbarosselimbuyukelci** [algolia/algoliasearch-inventory-magento-2#12]
I saw a pull request created 6 days ago by @mohitalgolia 

We urgently need this module to be compatible with Magento 2.4.x version. 

We also have a support ticket on Algolia Support as well. 

@rakesh-algolia please review the pending PR as soon as you can and have a new release so we can update through composer.

**Comment by rachel-trott** [comment]
We have released the update for Magento 2.4.x

**Comment by barbarosselimbuyukelci** [comment]
Thank you, installed it and reindex a spesific sku to see if the stock status is going to reflect to the related store but seems the opposite. 

Have a product that doesn't have any stock quantities in any assigned sources for the website but it still shows as in stock in Algolia.

Please refer below screenshots;

![Screenshot_2](https://user-images.githubusercontent.com/17678347/178601678-db005360-d962-437f-98f0-93fea33bf9df.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/17678347/178601679-5e5482a5-f350-4861-9533-7fc52bd9f486.jpg)

**Comment by barbarosselimbuyukelci** [comment]
Hello Ratikant,

No we've started using Algolia after enabled the MSI. Products are assigned to sources for too long now, each new created product is being assigned to all sources and each source connected to a spesific website.

**Comment by ratikant-singh** [comment]
Hi Barbaros,

you have multi website setup right, so you are using same indexes for your multi website or it is different for each website?

**Comment by barbarosselimbuyukelci** [comment]
The indexes in Algolia are different for each store-view because we have Country -> Language (English and Arabic) structure. 

So each website has 2 storeviews one for english and one store view for arabic. 

Also each website has their own "source" assigned to the website.

**Comment by ratikant-singh** [comment]
Can you check for that  product, is there any multiple source assigned? or in any one source it is in stock

**Comment by barbarosselimbuyukelci** [comment]
Of course multiple sources assigned to the product but sources connected to the website has 0 stock. 

![Screenshot_1](https://user-images.githubusercontent.com/17678347/178700252-da27ce93-417c-4190-bb5d-6bb112c9b371.jpg)

**Comment by ratikant-singh** [comment]
Can you please check stock id associated the website, 
And check if there is stock information available in the database table - inventory_stock_{stock_id} for example - inventory_stock_3

**Comment by barbarosselimbuyukelci** [comment]
Hello Ratikanth, yes they all there it's not a single product case, all products are the same.

**Comment by barbarosselimbuyukelci** [comment]
In Algolia I only have fields in the attached screenshot. Product is not salable and the quantity is zero. You can check it yourself;

https://www.tavolashop.com/ae-en/wilton-angel-food-pan-10-in?queryID=85d643ed35d2c89352f9eaed42ceacfd&objectID=3546&indexName=production_ae-en_products

![resim](https://user-images.githubusercontent.com/17678347/178723465-be073da2-a399-4ad2-b816-c9c45c8e1595.png)

**Comment by ratikant-singh** [comment]
As you see I am below Image I have created the website and and assigned the multiple source

<img width="1369" alt="Screen Shot 2022-07-13 at 8 34 02 PM" src="https://user-images.githubusercontent.com/101382014/178766783-759b4f34-0e88-44c0-96bc-bd21b3db9b8d.png">

Right Now I don't have product in stock it is not showing in the  algolia dashboard

<img width="1367" alt="Screen Shot 2022-07-13 at 8 37 18 PM" src="https://user-images.githubusercontent.com/101382014/178767442-ccb902be-e224-4438-aea4-8bc53c675fd0.png">

Now I have updated the one of the source quantity as 100

<img width="1367" alt="Screen Shot 2022-07-13 at 8 39 51 PM" src="https://user-images.githubusercontent.com/101382014/178768001-08b416f2-4a3c-43f6-908d-3b2866d4f914.png">

It is showing correctly at algolia side.
<img width="874" alt="Screen Shot 2022-07-13 at 8 41 32 PM" src="https://user-images.githubusercontent.com/101382014/178768404-204096b5-20e9-4e9c-b101-fa3efff4b4c4.png">

This is working fine. I am not able to reproduce.

If you need any additional Support please contact us at [support@algolia.com](mailto:support@algolia.com)

**Comment by barbarosselimbuyukelci** [comment]
Hello Ratikanth, in your screenshot in_stock is also equals to 1 which means Algolia is showing searches that are not in stock. I don't understand did you take the screenshot after adding stock to the source or before? 

Because my problem is to be very clear, Algolia is showing products that are not in stock which something we don't want and something the support told us to use this extension to solve that problem.

So based on that if I don't have any stocks to any sources connected to a website, products in that website's index should be out of stock not in stock, right?

Thats exactly what my problem is.

**Comment by ratikant-singh** [comment]
We tested the scenario, when product is out of stock in a source, algolia will not have that product in corresponding index.

We also set separate indexes for separate websites. This case is working as expected. 

We are closing this issue cannot be replicated.
